# Generated by Django 4.0.5 on 2022-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dungeon_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
