# Generated by Django 4.0.5 on 2022-07-25 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WonderousItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('islegendary', models.BooleanField(default=False, verbose_name='Legendary')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('islegendary', models.BooleanField(default=False, verbose_name='Legendary')),
                ('attunement', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('simple', 'Simple'), ('martial', 'Martial')], max_length=10)),
                ('attack', models.CharField(blank=True, choices=[('melee', 'Melee'), ('ranged', 'Ranged')], max_length=10)),
                ('damagetype', models.CharField(blank=True, choices=[('slashing', 'Slashing'), ('bludgeoning', 'Bludgeoning'), ('piercing', 'Piercing')], max_length=20, verbose_name='Damage type')),
                ('weapontype', models.CharField(blank=True, max_length=20, verbose_name='Weapon type')),
                ('damage', models.CharField(blank=True, max_length=8)),
                ('bonus', models.CharField(blank=True, max_length=3)),
                ('properties', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('spell_level', models.CharField(blank=True, max_length=10, verbose_name='Spell level')),
                ('school', models.CharField(max_length=50)),
                ('casting_time', models.CharField(max_length=50, verbose_name='Casting time')),
                ('range', models.CharField(max_length=50)),
                ('target', models.CharField(blank=True, max_length=50)),
                ('components', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('higher_levels', models.CharField(max_length=200, verbose_name='Higher level cast')),
                ('spell_lists', models.CharField(max_length=100, verbose_name='Spell list')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PotionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArmorItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('islegendary', models.BooleanField(default=False, verbose_name='Legendary')),
                ('weightdisadvantage', models.BooleanField(default=False, verbose_name='Weight Disadvantage')),
                ('attunement', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('heavy', 'Heavy'), ('medium', 'Medium'), ('light', 'Light')], max_length=15)),
                ('armorclass', models.IntegerField(verbose_name='AC')),
                ('armortype', models.CharField(blank=True, max_length=15, verbose_name='Armor type')),
                ('bonus', models.CharField(max_length=3)),
                ('properties', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
