# Generated by Django 4.0.5 on 2022-09-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_armoritem_armortype_alter_armoritem_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potionitem',
            name='properties',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='wonderousitem',
            name='properties',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
