# Generated by Django 4.0.5 on 2022-09-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_potionitem_properties_wonderousitem_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armoritem',
            name='properties',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='potionitem',
            name='properties',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='weaponitem',
            name='properties',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wonderousitem',
            name='properties',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
