# Generated by Django 4.0.5 on 2022-09-13 15:19

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_armoritem_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armoritem',
            name='description',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='armoritem',
            name='name',
            field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='potionitem',
            name='description',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='potionitem',
            name='name',
            field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='spellitem',
            name='description',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='spellitem',
            name='name',
            field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='weaponitem',
            name='category',
            field=models.CharField(choices=[('simple', 'Simple'), ('martial', 'Martial')], max_length=10, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='weaponitem',
            name='damage',
            field=models.CharField(max_length=8, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='weaponitem',
            name='description',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='weaponitem',
            name='name',
            field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='weaponitem',
            name='properties',
            field=models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='weaponitem',
            name='weapontype',
            field=models.CharField(max_length=20, validators=[profanity.validators.validate_is_profane], verbose_name='Weapon type'),
        ),
        migrations.AlterField(
            model_name='wonderousitem',
            name='description',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='wonderousitem',
            name='name',
            field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
